### ISSUE TITLE
'date' option doesn't work as expected based on examples in the README

### ISSUE THREAD

**Issue by benjaminjackson** [databox/databox-ruby#5]
Dates are stripped from the options hash before being sent to Databox here: https://github.com/databox/databox-ruby/blob/c6356b6d6452883aa03f54a8ed40db0fab2403d2/lib/databox/client.rb#L41

Because of this, it's impossible to use the #push and #insert_all methods to backfill data.

**Comment by VladaPetrovic** [comment]
@benjaminjackson thanks for the feedback. It was a bug. It's fixed now in `2.0.1`
